#! /bin/bash
#
# DynamicGraph:  Customized Ganglia dynamic metric daemon
#
# chkconfig: - 90 60
# description: DynamicGraphh is a customized Ganglia dynamic metric daemon written for Nanigans
# processname: DynamicGraph
# pidfile: /var/run/DynamicGraph.pid
# Source function library.

. /etc/init.d/functions

# chkconfig --add DynamicGraph when done
#
# /etc/DynamicGraph.cfg holds configurable options
#

RETVAL=0

# See how we were called.

prog="DynamicGraph"
PIDFILE="/var/run/DynamicGraph.pid"
DynamicGraph="/usr/local/sbin/DynamicGraph"
DAEMON_USER="root"
DAEMON_OPTS=""


start() {
	echo -n $"Starting $prog: "

	/usr/local/sbin/DynamicGraph &
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/DynamicGraph
    sleep 1
    PID=`ps -ef | grep '[p]ython /usr/local/sbin/DynamicGraph' | awk '{ print $2 }'`
    echo $PID > $PIDFILE
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	killproc DynamicGraph 2>/dev/null
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/DynamicGraph
    rm -rf $PIDFILE
	return $RETVAL
}

rhstatus() {
	status DynamicGraph
}

restart() {
  	stop
	start
}

reload() {
	echo -n $"Reloading DynamicGraph daemon configuration: "
	killproc DynamicGraph -HUP
	retval=$?
	echo
	return $RETVAL
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  reload)
  	reload
	;;
  status)
  	rhstatus
	;;
  condrestart)
  	[ -f /var/lock/subsys/DynamicGraph ] && restart || :
	;;
  *)
	echo $"Usage: $0 {start|stop|status|reload|restart|condrestart}"
	exit 1
esac

exit $?
